### ISSUE TITLE
The Zip Archieve File Corrupt when Extracted

### ISSUE THREAD

**Issue by suryodanar** [PhilippImhof/moodle-quiz_essaydownload#5] opened 2024-08-05 06:29 UTC
Thank You Phillipp for this amazing plugin on moodle. I have a problem when using it, after i submit the download button 
![Screenshot (373)](https://github.com/user-attachments/assets/b6e21356-f11b-4179-89f3-9081d0869bcd)

i have file in zip but when i try to extract the file it goes corrupt like this 
![Screenshot (374)](https://github.com/user-attachments/assets/6d5547cd-6097-4d36-b314-5d154edc89b5)

Is there any possible way to fix this problem ?

Thank You,
Regards

**Comment by PhilippImhof** [comment] 2024-08-05 09:43
Thanks for reaching out. I am sorry you have problems using the plugin. A few questions, trying to figure out what happened:

* Have you had quizzes where the export worked fine?
* Can you give me an overview of the quiz? (How many questions, what types?)
* Is it a real quiz with real data or would it be possible to share the ZIP file with me?

**Comment by suryodanar** [comment] 2024-08-06 02:26
Thank you for your fast response, 
I'll try to answer it

1. There's no one extracted file works fine
2. Just 1 Essay Question
3. Real Quiz for Remedial MidTerm Exam at My Campus
4. I will share it a few of them below  

[23C4A001_-_KSA_PA_2023_-_Ujian_Tengah_Semester_PA_Budha_-_210.zip](https://github.com/user-attachments/files/16504472/23C4A001_-_KSA_PA_2023_-_Ujian_Tengah_Semester_PA_Budha_-_210.zip)
[23C4A001_-_KSA_PA_2023_-_Ujian_Tengah_Semester_PA_Protestan_-_206.zip](https://github.com/user-attachments/files/16504473/23C4A001_-_KSA_PA_2023_-_Ujian_Tengah_Semester_PA_Protestan_-_206.zip)
[23C4A007T_-_KWN_2023_-_UTS_KSA_Kewarganegaraan_-_191.zip](https://github.com/user-attachments/files/16504474/23C4A007T_-_KWN_2023_-_UTS_KSA_Kewarganegaraan_-_191.zip)
[23C4A008T_-_P5_2023_-_UTS_KSA_Pancasila_-_193.zip](https://github.com/user-attachments/files/16504475/23C4A008T_-_P5_2023_-_UTS_KSA_Pancasila_-_193.zip)

**Comment by PhilippImhof** [comment] 2024-08-06 06:28
> Thank you for your fast response, I'll try to answer it

> 1. There's no one extracted file works fine
> 2. Just 1 Essay Question
> 3. Real Quiz for Remedial MidTerm Exam at My Campus
> 4. I will share it a few of them below  


Thanks. I will have a look and try to figure out what happens. Also, I will delete your last post to remove the files, just in case.

**Comment by suryodanar** [comment] 2024-08-06 07:56
thanks in advance for your help @PhilippImhof

**Comment by PhilippImhof** [comment] 2024-08-06 08:29
Another question popping up: Do you have any customisations, e.g. a special theme or anything?

**Comment by PhilippImhof** [comment] 2024-08-06 08:37
Trying not to disclose too much, but can you confirm that for the quiz "Ujian_Tengah_Semester_PA_Budha", there are supposed to be 15 students:
* Ang. Agn.
* Dar. Sub.
* Fra. Ang.
* Lav. Glo.
* Mig. Vel.
* Mo. Wij. Lyd.
* Mo. Wij. Liv.
* Sam. Suw. Kan.
* Seb Rai. Ric.
* Sub. Sam.
* Sur. Tri.
* Tan. Yol.
* Van. Ven.
* Wil. Nat.
* Win. Fin.

The data is there, but the ZIP file also contains a HTML error page generated by Moodle, so I am trying to find out where that error occurs. (It does not on my testing servers.)

**Comment by PhilippImhof** [comment] 2024-08-06 08:55
@suryodanar I don't know how comfortable you are with all this stuff, but would you mind trying to install the version from the [`fixcorruption` branch](https://github.com/PhilippImhof/moodle-quiz_essaydownload/tree/fixcorruption) and check whether the problem is resolved with that?

I cannot test it myself, because the error does not occur on my systems.

**Comment by suryodanar** [comment] 2024-08-06 09:33
> Trying not to disclose too much, but can you confirm that for the quiz "Ujian_Tengah_Semester_PA_Budha", there are supposed to be 15 students:
> 
> * Ang. Agn.
> * Dar. Sub.
> * Fra. Ang.
> * Lav. Glo.
> * Mig. Vel.
> * Mo. Wij. Lyd.
> * Mo. Wij. Liv.
> * Sam. Suw. Kan.
> * Seb Rai. Ric.
> * Sub. Sam.
> * Sur. Tri.
> * Tan. Yol.
> * Van. Ven.
> * Wil. Nat.
> * Win. Fin.
> 
> The data is there, but the ZIP file also contains a HTML error page generated by Moodle, so I am trying to find out where that error occurs. (It does not on my testing servers.)

Yeah it's right 
there's 15 students, 
but for  * Mo. Wij. Lyd.  & * Mo. Wij. Liv. both of them didn't submit the quiz but using text response on moodle

**Comment by PhilippImhof** [comment] 2024-08-06 09:35
Thanks for the confirmation. So all data is there and the ZIP is correctly prepared, it gets corrupted later in the process. The proposed fix should probably solve the issue.

**Comment by suryodanar** [comment] 2024-08-06 09:37
> @suryodanar I don't know how comfortable you are with all this stuff, but would you mind trying to install the version from the [`fixcorruption` branch](https://github.com/PhilippImhof/moodle-quiz_essaydownload/tree/fixcorruption) and check whether the problem is resolved with that?
> 
> I cannot test it myself, because the error does not occur on my systems.

Thank you, of course I will. Hope the problem can be resolved after this

**Comment by suryodanar** [comment] 2024-08-07 04:03
Hi, Thanks in advance @PhilippImhof 
I just want to share information, about 
your version from the [fixcorruption branch](https://github.com/PhilippImhof/moodle-quiz_essaydownload/tree/fixcorruption) already fix my problem until i try to know more and more and the problem still happen like this zip files
https://drive.google.com/file/d/19-LLYjp2AGCNVec9xWrq2xHY3mV2_Q6U/view?usp=sharing
(I can attatch direct from this so uses googledrive)
I've check randomly and still found error for the large file and long path name of zip file

**Comment by PhilippImhof** [comment] 2024-08-07 06:41
Thanks very much for your efforts and report. Checking your second ZIP files showed me another issue that should be fixed in the other branch. So if you have some time, I would appreciate if you could test it again.

**Comment by PhilippImhof** [comment] 2024-08-07 11:05
@suryodanar I have merged the PR. Please try the latest version from the main branch. It fixes the issue of corrupted ZIP archives and also includes better error reporting so we can track down other issues, if there are any. 

Thanks very much for your help. Once I hear back from you (with a hopefully positive feedback), I will prepare and publish a new release.

**Comment by suryodanar** [comment] 2024-08-08 01:13
thank you @PhilippImhof, I really love to try it again. Really grateful with your effort . Soon I'll report the result to you.

**Comment by suryodanar** [comment] 2024-08-08 01:23
and one more request if possible, usually in campus username for student is the student id number, 
when teacher / lecturer download the eassay submission, compare with the [last plugin](https://moodle.org/plugins/quiz_downloadsubmissions) we used is easier to identify when put the username as the first folder's name than lastname / firstname of students. 

here's the example of the download zip file from that plugin 
https://drive.google.com/file/d/1wbAQ44iVbAD7V5Jd6WRk79Iu6kdKaXzO/view?usp=sharing

**Comment by suryodanar** [comment] 2024-08-08 01:38
I've been test to download again, in first try get this error message
![image](https://github.com/user-attachments/assets/f6cd9e2c-dfb3-4f40-83dc-21504da0bcb3)
in one of the file Error0x80010135: Path too long

**Comment by PhilippImhof** [comment] 2024-08-08 06:40
Thanks for testing it again. That last issue is a [known Windows problem](https://www.makeuseof.com/how-to-fix-0x80010135-zip-extraction-error-windows-11-10).

I will open a separate issue for that and try to add some option. And I'll open another issue to add an option where the user can select the name ordering as First/Last or Last/First.

I am now closing this issue as solved, thanks again for your help while debugging. Feel free to comment again or to add comments to the two new issues.

**Comment by PhilippImhof** [comment] 2024-08-08 06:41
Fixed with PR #6

**Comment by PhilippImhof** [comment] 2024-08-08 06:41
Fixed with PR #6

**Closed as completed by PhilippImhof** 2024-08-08 06:41 UTC

**Comment by PhilippImhof** [comment] 2024-08-23 09:21
@suryodanar Just to let you know that I am currently preparing version 1.1.0 for a release later today. It will include an option that lets you choose between First/Last or Last/First name ordering.
