### ISSUE TITLE
Downloaded zip file is empty

### ISSUE THREAD

**Issue by aman5hah** [PhilippImhof/moodle-quiz_essaydownload#4] opened 2024-07-04 08:27 UTC
On Moodle 4.1 after clicking on Download button in Download essay responses tab, a zip fie will be downloaded but when i try to extract the zip file it fails with "the compressed zip folder is empty" error.

The quiz attempt isn't empty, there is 1 response that I can view in the Responses tab.

I'm sorry if this isn't quite detailed, I'm very new to this.

**Comment by PhilippImhof** [comment] 2024-07-04 09:53
Thanks for reaching out. 

First things first: Is it possible to share that ZIP with me? (If it is really empty, there should not be a problem. If it is not empty, i. e. if everything actually worked as intended, what data would it contain? If the data is not sensitive, you might upload it into this issue. You can just drag-and-drop it into the text field when replying.

Second, can you export the quiz and upload the resulting file here as well? Does the quiz actually contain an essay question or a random question that resolved to an essay question?

Third, is it a real attempt by a real student (enrolled in the course as student) or a test attempt, e.g. by a teacher in their teacher role or after a role-switch into the student role?

**Comment by PhilippImhof** [comment] 2024-08-07 11:06
@aman5hah I have made some changes. Please try to download the most recent version from the main branch and let me know if this solves your problems. If it does not, you will find more detailed error reports in the ZIP file.

**Comment by PhilippImhof** [comment] 2024-08-08 06:53
Closing this, as there has been no feedback for a while and it is most certainly solved by #6.

**Closed as completed by PhilippImhof** 2024-08-08 06:53 UTC
Labels: more information needed

**Comment by aman5hah** [comment] 2024-08-20 02:26
Hi, just writing to inform that I recently tried your current version 1.0.2 and the issue that I'm having is resolved. Thank you so much for the fix and the plugin.
